# Hyprland Config for Laptop 

source = ~/.config/hypr/config/env.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/binds.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/looks.conf
source = ~/.config/hypr/config/rules.conf
source = ~/.config/hypr/config/displays.conf
source = ~/.config/hypr/config/layouts.conf
