-- Nord colours
conky.config["nord0"]	= '#2e3440'
conky.config["nord1"]	= '#3b4252'
conky.config["nord2"]	= '#434c5e'
conky.config["nord3"]	= '#4c566a'
conky.config["nord4"]	= '#d8dee9'
conky.config["nord5"]	= '#e5e9f0'
conky.config["nord6"]	= '#eceff4'
conky.config["nord7"]	= '#8fbcbb'
conky.config["nord8"]	= '#88c0d0'
conky.config["nord9"]	= '#81a1c1'
conky.config["nord10"]	= '#5e81ac'
conky.config["nord11"]	= '#bf616a'
conky.config["nord12"]	= '#d08770'
conky.config["nord13"]	= '#ebcb8b'
conky.config["nord14"]	= '#a3be8c'
conky.config["nord15"]	= '#b48ead'

conky.config["own_window_colour"] = conky.config["nord0"]
conky.config["color1"]		  = conky.config["nord4"]
conky.config["color2"] 		  = conky.config["nord8"]
conky.config["color3"]		  = conky.config["nord9"]
conky.config["color4"] 	  	  = conky.config["nord10"]
conky.config["color5"] 	  	  = conky.config["nord11"]
conky.config["color6"] 	  	  = conky.config["nord12"]
conky.config["color7"] 	  	  = conky.config["nord13"]
conky.config["color8"] 	  	  = conky.config["nord14"]
conky.config["color9"] 	  	  = conky.config["nord15"]
