# Autostart:
## Wallpaper, Auth, Waybar, Sleep Scr, Night Light, Clipboard, etc.


exec-once = hyprpaper & /usr/lib/polkit-kde-authentication-agent-1 & dunst & waybar & ~/.config/hypr/scripts/sleep.sh & ~/.config/hypr/scripts/night_light.sh 

exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store

