# Window Rules

windowrule = match:title ^(Qalculate!)$, float on

windowrule = match:class ^(steam)$,  workspace 3 silent
windowrule = match:class ^(heroic)$, workspace 3 silent
windowrule = match:class ^(lutris)$, workspace 3 silent

windowrule = match:class ^(discord)$, workspace 4 silent
windowrule = match:title ^(mpv)$, workspace 5
windowrule = match:class ^(org\.pulseaudio\.pavucontrol)$, workspace 10


# Window Swallowing
misc {
    enable_swallow = true
    swallow_regex = ^(kitty)$
}


